language: node_js
node_js:
    - "7.7"
    - "6.10"
    - "5.12"
    - "4.8"
    - "0.12"
    - "0.10"
before_install:
    - npm install -g npm
before_script:
    - npm install -g grunt-cli
after_script:
    - grunt coverage
