language: node_js
node_js:
    - "6.2"
    - "5.11"
    - "4.4"
    - "0.12"
    - "0.10"
before_install:
    - npm install -g npm
before_script:
    - npm install -g grunt-cli
after_script:
    - grunt coverage
