on:
  push:
    branches:
    - "**"
  pull_request:
    branches:
    - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
        - 12.x
        - 14.x
        - 16.x
    steps:
    - uses: actions/checkout@v3
    - name: Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
    - run: npm install
    - run: npm test
    - run: npm coverage
