on: 
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:
jobs:
  publish:
    if: github.event.base_ref=='refs/heads/master'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: node scripts/preparePublish
    - run: cd publish
    - uses: JS-DevTools/npm-publish@v1
      with:
        dry-run: true
        token: ${{ secrets.NPM_TOKEN }}
