on: 
  push:
    tags:
      - "*"
  workflow_dispatch:
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        # to be able to get tags
        # when manually triggering
        fetch-depth: 0
    - name: NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
    - run: npm install
    - run: node test
    - run: node scripts/preparePublish "$( git describe --tags --abbrev=0 )"
    - run: |
        cd publish
        echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" > .npmrc
        npm publish
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
